/*
 * The MIT License
 *
 * Copyright 2015 Diego Geronimo D' Onofre.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package erpsystem.forms;

import erpsystem.Util;
import erpsystem.db.Estoque;
import erpsystem.db.EstoqueDB;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableModel;

import erpsystem.db.Produto;
import erpsystem.db.ProdutosDB;
import java.awt.event.KeyEvent;
        
/**
 *
 * @author Diego
 */
public class ConsultaProdutoView extends javax.swing.JDialog {

    /**
     * Creates new form ConsultaProdutoView
     */
    public ConsultaProdutoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        java.awt.Point p = Util.getCenterPoint(this.getWidth(), this.getHeight());
        this.setLocation(p);
        
        this.setTitle("Consulta Produtos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPesquisar = new javax.swing.JButton();
        lblDesc = new javax.swing.JLabel();
        tfdDesc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProds = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblDesc.setText("Descrição");

        tfdDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfdDescMousePressed(evt);
            }
        });
        tfdDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfdDescKeyPressed(evt);
            }
        });

        tblProds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código de Barras", "Descrição", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProds.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblProds);
        tblProds.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesc)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        initTab();
        search();
        afterConstruct();
    }//GEN-LAST:event_formWindowOpened

    private void search()
    {
        tblProds.setEnabled(false);
        String desc = tfdDesc.getText();
        java.util.List<Produto> prodList = ProdutosDB.findProd(desc);
        
        if ( prodList != null )
            fill(prodList);
        
        tblProds.setEnabled(true);         
    }
    
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tfdDescMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfdDescMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdDescMousePressed

    private void tfdDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdDescKeyPressed
        // TODO add your handling code here:
        int code = evt.getKeyCode();
        
        if ( code == KeyEvent.VK_ENTER )
            search();
    }//GEN-LAST:event_tfdDescKeyPressed

    final int COD_PROD     = 0;
    final int COD_BARRAS   = 1;
    final int DESC         = 2;
    final int PRECO_COMPRA = 3;      
    final int PRECO_VENDA  = 4;      
    final int ESTOQUE_QT   = 5;      
    
    private void fill(java.util.List<Produto> prodList)
    {
        TableModel newModel = new XTableModel(prodCols, prodList.size());
        
        for ( int i = 0; i < prodList.size(); i++ ){
            Produto prod = prodList.get(i);
            
            //Obtendo informações do produto.
            final int cod      = prod.getCodigo();
            String codBarras   = prod.getCodBarras();
            String desc        = prod.getDescricao();
            double precoCompra = prod.getPrecoCompra();
            double precoVenda  = prod.getPrecoVenda();
            
            //Obtendo o estoque do produto.
            Estoque estoque    = EstoqueDB.find(cod);
            int estoqueQt      = estoque.getQt();
            
            //Fixando as informações na tabela.   
            newModel.setValueAt(cod,         i, COD_PROD);
            newModel.setValueAt(codBarras,   i, COD_BARRAS);
            newModel.setValueAt(desc,        i, DESC);
            newModel.setValueAt(precoCompra, i, PRECO_COMPRA);
            newModel.setValueAt(precoVenda,  i, PRECO_VENDA);
            newModel.setValueAt(estoqueQt,   i, ESTOQUE_QT);

        }
        
        tblProds.setModel(newModel);
        tblProds.getColumnModel().getColumn(COD_PROD).setMinWidth(65);
        tblProds.getColumnModel().getColumn(COD_PROD).setMaxWidth(65);
    }     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaProdutoView dialog = new ConsultaProdutoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private final static Object[] prodCols = new Object[]{"Código",
                                                          "Código de barras",
                                                          "Descrição",
                                                          "Preço de compra",
                                                          "Preço de venda",
                                                          "Estoque Qt."
                                                        };
    
    private final TableModel emptyProdModel = new XTableModel(new Object[0][prodCols.length], prodCols);    
    
    public javax.swing.JTable getTblProds()
    {
        return this.tblProds;
    }
    
    private void initTab()
    {   
        //Bloqueando a reordenação das colunas
        tblProds.getTableHeader().setReorderingAllowed(false);
        //Evitando seleção múltipla
        tblProds.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
        tblProds.setModel(emptyProdModel);
        tblProds.getColumnModel().getColumn(COD_PROD).setMinWidth(65);
        tblProds.getColumnModel().getColumn(COD_PROD).setMaxWidth(65);
        tblProds.setDefaultRenderer(Object.class, Util.getDefaultCellRenderer());
    }      
    
    protected void afterConstruct()
    {}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JTable tblProds;
    private javax.swing.JTextField tfdDesc;
    // End of variables declaration//GEN-END:variables
}
