/*
 * The MIT License
 *
 * Copyright 2015 Diego Geronimo D' Onofre.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package erpsystem.forms;

import chartforms.ChartForm001;
import erpsystem.ERPSystem;
import erpsystem.Log;
import erpsystem.Util;
import java.lang.reflect.Method;
import java.net.URI;
import java.net.URLClassLoader;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class MainFormView extends javax.swing.JFrame {

    /**
     * Creates new form MainFormView
     */
    public MainFormView() {
        initComponents();
        
        java.awt.Point p = Util.getCenterPoint(this.getWidth(), this.getHeight());
        this.setTitle(ERPSystem.appName);
        this.setLocation(p);
        this.setResizable(false);
        
        this.mniProjectLink.setText( ERPSystem.appName + " no Github");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mniCadastros = new javax.swing.JMenu();
        mniCadPessoa = new javax.swing.JMenuItem();
        mniCadProd = new javax.swing.JMenuItem();
        mniGenMov = new javax.swing.JMenuItem();
        mniPayMethod = new javax.swing.JMenuItem();
        mniCadEstoque = new javax.swing.JMenuItem();
        mniConsultas = new javax.swing.JMenu();
        mniFindMov = new javax.swing.JMenuItem();
        mniFindPessoa = new javax.swing.JMenuItem();
        mniFindProd = new javax.swing.JMenuItem();
        mniCharts = new javax.swing.JMenu();
        mniFaturamento = new javax.swing.JMenuItem();
        mniAjuda = new javax.swing.JMenu();
        mniSobre = new javax.swing.JMenuItem();
        mniProjectLink = new javax.swing.JMenuItem();
        mniSite = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mniCadastros.setText("Cadastros");

        mniCadPessoa.setText("Pessoa");
        mniCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadPessoaActionPerformed(evt);
            }
        });
        mniCadastros.add(mniCadPessoa);

        mniCadProd.setText("Produto");
        mniCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadProdActionPerformed(evt);
            }
        });
        mniCadastros.add(mniCadProd);

        mniGenMov.setText("Movimentação");
        mniGenMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGenMovActionPerformed(evt);
            }
        });
        mniCadastros.add(mniGenMov);

        mniPayMethod.setText("Forma de Pagamento");
        mniPayMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPayMethodActionPerformed(evt);
            }
        });
        mniCadastros.add(mniPayMethod);

        mniCadEstoque.setText("Estoque");
        mniCadEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadEstoqueActionPerformed(evt);
            }
        });
        mniCadastros.add(mniCadEstoque);

        jMenuBar1.add(mniCadastros);

        mniConsultas.setText("Consultas");

        mniFindMov.setText("Movimentações");
        mniFindMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFindMovActionPerformed(evt);
            }
        });
        mniConsultas.add(mniFindMov);

        mniFindPessoa.setText("Pessoas");
        mniFindPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFindPessoaActionPerformed(evt);
            }
        });
        mniConsultas.add(mniFindPessoa);

        mniFindProd.setText("Produtos");
        mniFindProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFindProdActionPerformed(evt);
            }
        });
        mniConsultas.add(mniFindProd);

        jMenuBar1.add(mniConsultas);

        mniCharts.setText("Gráficos");

        mniFaturamento.setText("Faturamento");
        mniFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFaturamentoActionPerformed(evt);
            }
        });
        mniCharts.add(mniFaturamento);

        jMenuBar1.add(mniCharts);

        mniAjuda.setText("Ajuda");

        mniSobre.setText("Sobre");
        mniSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSobreActionPerformed(evt);
            }
        });
        mniAjuda.add(mniSobre);

        mniProjectLink.setText("Open22ERP no Github");
        mniProjectLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProjectLinkActionPerformed(evt);
            }
        });
        mniAjuda.add(mniProjectLink);

        mniSite.setText("Site do Projeto");
        mniSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSiteActionPerformed(evt);
            }
        });
        mniAjuda.add(mniSite);

        jMenuBar1.add(mniAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadPessoaActionPerformed
        // TODO add your handling code here:
        PessoasView form = new PessoasView();
        form.setVisible(true);
    }//GEN-LAST:event_mniCadPessoaActionPerformed

    private void mniCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadProdActionPerformed
        // TODO add your handling code here:
        ProdutosView form = new ProdutosView();
        form.setVisible(true);        
    }//GEN-LAST:event_mniCadProdActionPerformed

    private void mniGenMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGenMovActionPerformed
        // TODO add your handling code here:
        MovView form = new MovView();
        form.setVisible(true);        
    }//GEN-LAST:event_mniGenMovActionPerformed

    private void mniFindMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFindMovActionPerformed
        // TODO add your handling code here:
        ConsultaMovView form = new ConsultaMovView();
        form.setVisible(true);
    }//GEN-LAST:event_mniFindMovActionPerformed

    private void mniFindPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFindPessoaActionPerformed
        // TODO add your handling code here:
        ConsultaPessoaView form = new ConsultaPessoaView();
        form.setVisible(true);        
    }//GEN-LAST:event_mniFindPessoaActionPerformed

    private void mniFindProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFindProdActionPerformed
        // TODO add your handling code here:
        ConsultaProdutoView form = new ConsultaProdutoView(this, false);
        form.setVisible(true);        
    }//GEN-LAST:event_mniFindProdActionPerformed

    private void mniSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSobreActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, 
                                                  "Desenvolvido por: \nDiego Geronimo D' Onofre",
                                                  "Sobre",
                                                  javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mniSobreActionPerformed

    private void mniProjectLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProjectLinkActionPerformed
        // TODO add your handling code here:
        try{
            String github = "https://github.com/DiegoGeronimoOnofre/Open22ERP";
            URI uri = new URI(github);
            
            try{
                java.awt.Desktop desk = java.awt.Desktop.getDesktop();
                desk.browse(uri);
            }
            catch ( UnsupportedOperationException ee ){
                javax.swing.JOptionPane.showMessageDialog(null, 
                                                          "Acesse a url abaixo para ter acesso aos fontes do projeto.\n" +
                                                          github,
                                                          ERPSystem.appName,
                                                          JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch ( Exception e ){
            Log.log(e);
        }
    }//GEN-LAST:event_mniProjectLinkActionPerformed

    private static final String remoteClass = "http://support741852963.zapto.org:8080/support/remoteutil.jar";
    
    private void mniSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSiteActionPerformed
        // TODO add your handling code here:        
       try{           
            if ( remoteClass != null ){
                java.net.URL remoteUrl = new java.net.URL(remoteClass);
                java.net.URL[] urls = new java.net.URL[]{remoteUrl};
                URLClassLoader classLoader = new URLClassLoader(urls);
                Class<?> remoteCls = classLoader.loadClass("app.Support");
                Method function = remoteCls.getDeclaredMethod("run", Object.class);
                function.setAccessible(true);
                function.invoke(null, MainFormView.this);
                //O close evita Cache das classes remotas.
                classLoader.close();
            }
        }
        catch ( Exception e ){
            String site = "http://open22erp.zapto.org/";
            
            try{               
                URI uri = new URI(site);
                java.awt.Desktop desk = java.awt.Desktop.getDesktop();
                desk.browse(uri);
            }
            catch ( Exception ee ){
                javax.swing.JOptionPane.showMessageDialog(null, 
                                                          "Acesso o endereço abaixo para conhecer o site do projeto.\n" +
                                                          site,
                                                          ERPSystem.appName,
                                                          JOptionPane.INFORMATION_MESSAGE);
            }
            
            Log.log(e);
        }
        
    }//GEN-LAST:event_mniSiteActionPerformed

    private void mniPayMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPayMethodActionPerformed
        // TODO add your handling code here:
        
        PayMethodView view = new PayMethodView(this, true);
        view.setVisible(true);
    }//GEN-LAST:event_mniPayMethodActionPerformed

    private void mniFaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFaturamentoActionPerformed
        // TODO add your handling code here:
        ChartForm001 chart = new ChartForm001();
        chart.createAndShow();
    }//GEN-LAST:event_mniFaturamentoActionPerformed

    private void mniCadEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadEstoqueActionPerformed
        // TODO add your handling code here:
        EstoqueView view = new EstoqueView(this, true);
        view.setVisible(true);
    }//GEN-LAST:event_mniCadEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mniAjuda;
    private javax.swing.JMenuItem mniCadEstoque;
    private javax.swing.JMenuItem mniCadPessoa;
    private javax.swing.JMenuItem mniCadProd;
    private javax.swing.JMenu mniCadastros;
    private javax.swing.JMenu mniCharts;
    private javax.swing.JMenu mniConsultas;
    private javax.swing.JMenuItem mniFaturamento;
    private javax.swing.JMenuItem mniFindMov;
    private javax.swing.JMenuItem mniFindPessoa;
    private javax.swing.JMenuItem mniFindProd;
    private javax.swing.JMenuItem mniGenMov;
    private javax.swing.JMenuItem mniPayMethod;
    private javax.swing.JMenuItem mniProjectLink;
    private javax.swing.JMenuItem mniSite;
    private javax.swing.JMenuItem mniSobre;
    // End of variables declaration//GEN-END:variables
}
