/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package erpsystem.forms;

import erpsystem.Util;
import erpsystem.db.PayMethodDB;
import javax.swing.JFrame;

/**
 *
 * @author developer
 */
public class PayMethodView extends javax.swing.JDialog {

    /**
     * Creates new form PayMethodView
     */
    public PayMethodView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        java.awt.Point p = Util.getCenterPoint(this.getWidth(), this.getHeight());
        this.setLocation(p);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("Forma de Pagamento");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfdSalvar = new javax.swing.JButton();
        lblPayMethod = new javax.swing.JLabel();
        tfdPayMethod = new javax.swing.JTextField();
        tfdLimite = new javax.swing.JTextField();
        lblLimite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tfdSalvar.setText("Salvar");
        tfdSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdSalvarActionPerformed(evt);
            }
        });

        lblPayMethod.setText("Forma de pagamento");

        lblLimite.setText("Limite de dias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdPayMethod)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPayMethod)
                            .addComponent(lblLimite)
                            .addComponent(tfdSalvar))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPayMethod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfdPayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLimite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfdLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(tfdSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdSalvarActionPerformed
        // TODO add your handling code here:
        
        if ( validateFields() ){
            String payMethodValue = tfdPayMethod.getText();
            String limite = tfdLimite.getText();
            int intLimite = Integer.parseInt(limite);
            
            erpsystem.db.PayMethod payMethod = new erpsystem.db.PayMethod();
            payMethod.setDescricao(payMethodValue);
            payMethod.setLimite(intLimite);
            
            if (! PayMethodDB.exists(payMethodValue) )
                erpsystem.db.PayMethodDB.add(payMethod);
            else
                javax.swing.JOptionPane.showMessageDialog(null, "Forma de pagamento já cadastrada.");
        }
    }//GEN-LAST:event_tfdSalvarActionPerformed

    boolean validateFields()
    {
        if ( tfdPayMethod.getText().trim().equals("") ){
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor, informe o método de pagamento.");
            tfdPayMethod.grabFocus();
            return false;
        }  

        String limite = tfdLimite.getText().trim();
        
        if ( limite.equals("") ){
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor, informe o limite de dias.");
            tfdLimite.grabFocus();
            return false;
        }  
        
        if ( !Util.isInt(limite) ){
            javax.swing.JOptionPane.showMessageDialog(null, "Informe um número válido para o limite.");
            tfdLimite.grabFocus();
            return false;
        }
          
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayMethodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayMethodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayMethodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayMethodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PayMethodView dialog = new PayMethodView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLimite;
    private javax.swing.JLabel lblPayMethod;
    private javax.swing.JTextField tfdLimite;
    private javax.swing.JTextField tfdPayMethod;
    private javax.swing.JButton tfdSalvar;
    // End of variables declaration//GEN-END:variables
}
