/*
 * The MIT License
 *
 * Copyright 2015 Diego Geronimo D' Onofre.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package erpsystem.forms;

import erpsystem.Util;
import static erpsystem.Util.*;
import erpsystem.db.Produto;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Diego
 */
public class ProdutosView extends javax.swing.JFrame {

    /**
     * Creates new form Produto
     */
    public ProdutosView() {
        initComponents();
        
        java.awt.Point p = Util.getCenterPoint(this.getWidth(), this.getHeight());
        this.setLocation(p);
        this.setResizable(false);
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("Cadastro de Produtos");
        
        tfdPrecoCompra.setToolTipText("Exemplo: 8.99");
        tfdPrecoVenda.setToolTipText("Exemplo: 299.90");
        tfdPrecoCompra.setFont(new Font("Times New Roman", Font.BOLD, 12));
        tfdPrecoVenda.setFont(new Font("Times New Roman", Font.BOLD, 12));
        
        tfdPrecoCompra.setHorizontalAlignment(JTextField.RIGHT); 
        tfdPrecoVenda.setHorizontalAlignment(JTextField.RIGHT); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCad = new javax.swing.JButton();
        lblDesc = new javax.swing.JLabel();
        tfdDesc = new javax.swing.JTextField();
        tfdCodBarras = new javax.swing.JTextField();
        lblCodBarras = new javax.swing.JLabel();
        tfdPrecoCompra = new javax.swing.JTextField();
        lblPrecoCompra = new javax.swing.JLabel();
        lblPrecoVenda = new javax.swing.JLabel();
        tfdPrecoVenda = new javax.swing.JTextField();
        lblCompraValidator = new javax.swing.JLabel();
        lblVendaValidator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        lblDesc.setText("Descrição");

        lblCodBarras.setText("Código de barras");

        tfdPrecoCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfdPrecoCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfdPrecoCompraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdPrecoCompraKeyReleased(evt);
            }
        });

        lblPrecoCompra.setText("Preço de compra R$");

        lblPrecoVenda.setText("Preço de venda R$");

        tfdPrecoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfdPrecoVendaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdPrecoVendaKeyReleased(evt);
            }
        });

        lblCompraValidator.setText("...");

        lblVendaValidator.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfdPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCompraValidator))
                            .addComponent(lblPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfdPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblVendaValidator))
                            .addComponent(lblPrecoVenda))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblDesc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCodBarras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfdCodBarras, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(tfdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(143, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodBarras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfdCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrecoCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompraValidator))
                .addGap(12, 12, 12)
                .addComponent(lblPrecoVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVendaValidator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnCad)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validateFields()
    {
        if ( tfdCodBarras.getText().trim().equals("") )
        {
            msg("Por favor, informe o código de barras do produto.");
            tfdCodBarras.grabFocus();
            return false;        
        }
        
        if ( tfdDesc.getText().trim().equals("") )
        {
            msg("Por favor, informe uma descrição para o produto.");
            tfdDesc.grabFocus();
            return false;        
        }
        
        
        //Validando os preços.    
        
        if ( validatePreco(tfdPrecoCompra, "compra") == false )
            return false;
        
        if ( validatePreco(tfdPrecoVenda, "venda") == false )
            return false;
                
        return true;
    }
    
    private boolean validatePreco(JTextField tfdPreco, String name)
    {
        String preco = tfdPreco.getText().trim();
        
        if ( preco.equals("") ){
            msg("Por favor, informe um preço de " + name + " para produto.");
            tfdPreco.grabFocus();
            return false;        
        }
        
        if (! isDouble(preco) ){
            msg(
              "O sistema trabalha com o padrão americano para valores,\n"
              + "por isso é necessário substituir a vírgula \",\" por um ponto \".\"\n"
              + "para separar os centavos."
              + "Exemplos: 45.23  58.25  100");
            tfdPreco.grabFocus();
            return false;
        }
        
        if (Double.parseDouble(preco) <= 0 ){
            msg("O preço de " + name + " do produto deve ser igual ou superior a zero.");
            tfdPreco.grabFocus();
            return false;
        }     
        
        return true;
    }
    
    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        // TODO add your handling code here:
        if ( validateFields() ){
            Produto prod = new Produto();

            String codBarras   = tfdCodBarras.getText();
            String desc        = tfdDesc.getText();
            double precoCompra = Double.parseDouble(tfdPrecoCompra.getText());
            double precoVenda  = Double.parseDouble(tfdPrecoVenda.getText());

            prod.setCodBarras(codBarras);
            prod.setDescricao(desc);
            prod.setPrecoCompra(precoCompra);
            prod.setPrecoVenda(precoVenda);
            
            /**
             * Este método abaixo injeta o código do produto
             * no objeto passado como parâmetro "Produto"
             * depois que tem certeza que o produto foi cadastrado.
             */
            
            boolean result = business.Produtos.add(prod);
            
            if ( result ){
                clearFields();
                int opt = JOptionPane.showConfirmDialog(null, 
                                                          " Gostaria de adicionar estoque\n"
                                                        + " para o produto recem cadastrado? Se o\n"
                                                        + " estoque do produto recem cadastrado\n"
                                                        + " não for atualizado o sistema irá considerar\n"
                                                        + " que não há estoque para o mesmo.", 
                                                          "Atualizar Estoque", 
                                                          JOptionPane.YES_NO_OPTION);
                
                if ( opt == JOptionPane.YES_OPTION ){
                    int codProd = prod.getCodigo();
                    EstoqueView estoqueView = new EstoqueView(null, true);
                    estoqueView.setCodProd(codProd);
                    estoqueView.setVisible(true);
                }
                
                tfdCodBarras.grabFocus();
                tfdPrecoCompra.setBackground(Color.white); 
                tfdPrecoVenda.setBackground(Color.white); 
           }
            else
                msg("Problema ao cadastrar o novo produto.\n"
                  + "Recomendável tentar novamente, se o problema \n"
                  + "persistir informe o Desenvolvedor.");
        }
    }//GEN-LAST:event_btnCadActionPerformed

    private void tfdPrecoCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdPrecoCompraKeyPressed
        // TODO add your handling code here:
      /*  char c = evt.getKeyChar();
        
        if ( c == ',' )
            lblCompraValidator.setText("Troque a ',' por '.'");
        else
            lblCompraValidator.setText("...");*/

    }//GEN-LAST:event_tfdPrecoCompraKeyPressed

    private void tfdPrecoCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdPrecoCompraKeyReleased
        // TODO add your handling code here:       
        String value = tfdPrecoCompra.getText();       
        
        if ( !value.trim().equals("") ){
            if ( Util.isDouble(value) ){
                if ( value.length() > 1 && value.charAt(0) == '.' )
                    tfdPrecoCompra.setBackground(new Color(255, 115, 115)); 
                else{    
                    tfdPrecoCompra.setBackground(new Color(150, 255, 150));
                    lblCompraValidator.setText("...");
                }
            }
            else{
                tfdPrecoCompra.setBackground(new Color(255, 115, 115)); 
                
                if  (value.indexOf(',') != -1)
                    lblCompraValidator.setText("Troque a ',' por '.'");
            }
        }
        else
            tfdPrecoCompra.setBackground(Color.white);
    }//GEN-LAST:event_tfdPrecoCompraKeyReleased

    private void tfdPrecoVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdPrecoVendaKeyReleased
        // TODO add your handling code here:
        String value = tfdPrecoVenda.getText();       
        
        if ( !value.trim().equals("") ){
            if ( Util.isDouble(value) ){
                if ( value.length() > 1 && value.charAt(0) == '.' )
                    tfdPrecoVenda.setBackground(new Color(255, 115, 115)); 
                else{                 
                    tfdPrecoVenda.setBackground(new Color(150, 255, 150));
                    lblVendaValidator.setText("...");
                }
            }
            else{
                tfdPrecoVenda.setBackground(new Color(255, 115, 115));   
                
                if  (value.indexOf(',') != -1)
                    lblVendaValidator.setText("Troque a ',' por '.'");
            }
        }
        else
            tfdPrecoVenda.setBackground(Color.white);        
    }//GEN-LAST:event_tfdPrecoVendaKeyReleased

    private void tfdPrecoVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdPrecoVendaKeyPressed
        // TODO add your handling code here:
       /* char c = evt.getKeyChar();
        
        if ( c == ',' )
            lblVendaValidator.setText("Troque a ',' por '.'");
        else
            lblVendaValidator.setText("...");  */      
    }//GEN-LAST:event_tfdPrecoVendaKeyPressed
    
    private void clearFields()
    {
        tfdCodBarras.setText("");
        tfdDesc.setText("");
        tfdPrecoCompra.setText("");
        tfdPrecoVenda.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JLabel lblCodBarras;
    private javax.swing.JLabel lblCompraValidator;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblPrecoCompra;
    private javax.swing.JLabel lblPrecoVenda;
    private javax.swing.JLabel lblVendaValidator;
    private javax.swing.JTextField tfdCodBarras;
    private javax.swing.JTextField tfdDesc;
    private javax.swing.JTextField tfdPrecoCompra;
    private javax.swing.JTextField tfdPrecoVenda;
    // End of variables declaration//GEN-END:variables
}
